name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt install gdebi -y && sudo wget https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.amd64.deb && sudo gdebi -n devkitpro-pacman.amd64.deb && sudo rm devkitpro-pacman.amd64.deb && sudo dkp-pacman -S ppc-zlib ppc-libpng ppc-mxml ppc-freetype && cd wiipax && make && cd ../channel && make
